### ISSUE TITLE
Compiling error in sample project

### ISSUE THREAD

**Issue by JoseSanchezMirandaRos** [dualav/XGPS-SDK-iOS#1]
class WaitingToConnectView: UIView {
    
    init() {
        super.init(frame: getFrame())
        backgroundColor = UIColor.clear
    }

Error: 'self' used in method call 'getFrame' before 'super.init' call

**Comment by dualav** [comment]
super.init(frame: CGRect(x: 0, y: 0, width: 0, height: 0))
i had commit.
