### ISSUE TITLE
[BUG] Receiving "senetence checksum failed" error in puck.m after connecting with XGPS160 device

### ISSUE THREAD

**Issue by chris-gaona** [dualav/XGPS-SDK-iOS#11]
I'm receiving a "senetence checksum failed" error within puck.m when retrieving data from the XGPS160 device. The connection to this device is successful & I'm able to receive data for the "PuckConnected", "PuckDisconnected", & "PuckDataUpdated" events. The error occurs within the "PositionDataUpdated" event seemingly at the following line in puck.m:

<img width="851" alt="Screenshot 2023-06-16 at 2 39 58 PM" src="https://github.com/dualav/XGPS-SDK-iOS/assets/14164974/fb468200-da2b-45fe-a256-dffc903cf3db">

To clarify, I'm not seeing this same issue for the "XGPS150" device...only for the 160 device.

Any help would be greatly appreciated. I'm going to look into it myself & see if it's a simply fix but I wanted to bring it to your attention. Thanks!

**Comment by chris-gaona** [comment]
I'm marking this issue as resolved because I noticed my XGPS160 device's firmware was not up to date. Once I updated the firmware to the latest the issue went away. Thanks!

**Comment by Nick-Zhang1996** [comment]
@chris-gaona Hey Chris. Did you end up publishing your app? How did you get your app added to the list of approved apps with the XGPS160 Mfi accessory? Thanks!
