### ISSUE TITLE
Missing type 'LogData' after Download Example and Start in Xcode 11.3.1

### ISSUE THREAD

**Issue by Skyb0rg** [dualav/XGPS-SDK-iOS#5]
Hi, 
hope somebody can help me.

I get the following error when compiling the app.
How should i fix this?

**Use of undeclared type 'LogData'**

Thank you.

**Comment by Skyb0rg** [comment]
OK found it, sorry!

For all others out there -> If downloading the Projekt direct to Xcode.

LogData.swift was missing.

You can download it, it is in this repository:
XGPS-SDK-iOS/XGPSSample/XGPSSDK/LogData.swift

**Comment by JoseSanchezMirandaRos** [comment]
@Skyb0rg Have you gotten this SDK to work?

**Comment by Skyb0rg** [comment]
Yes without problems current Xcode 11.4 and Swift5

Dont forget to add xgps device string in Info.plist

See in the example Project.

**Comment by JoseSanchezMirandaRos** [comment]
> Yes without problems current Xcode 11.4 and Swift5
> 
> Dont forget to add xgps device string in Info.plist
> 
> See in the example Project.

Thanks! that fixed it!
