### ISSUE TITLE
App Store Rejection - MFi PPID missing

### ISSUE THREAD

**Issue by JoseSanchezMirandaRos** [dualav/XGPS-SDK-iOS#6]
Apple:

We have started your app review but are unable to complete the review because we cannot locate the MFi Product Plan ID (PPID)

Has anybody encountered this?

Thanks!

**Comment by PezHead** [comment]
You will need to email `cs@dualav.com` to help take care of that. They will need a few pieces of information such as App Name, Version, BundleID and a description. They will then be able to register your app, and provide you with their PPID. Hope that helps!
